image: python:3.11

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - /^v\d+\.\d+\.\d+$/
  before_script:
    # Install SSH client if not already present
    - "which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)"
    # Start SSH agent and add private key
    - echo "Host ${DEPLOY_HOST}"
    - echo "User ${DEPLOY_USER}"
    - eval $(ssh-agent -s)
    - chmod 600 "${SSH_PRIVATE_KEY}"
    - ssh-add "${SSH_PRIVATE_KEY}"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

  script:
    - scp -r -v src requirements.txt $DEPLOY_USER@$DEPLOY_HOST:/scripts/opm-scraper/
    - ssh $DEPLOY_USER@$DEPLOY_HOST "
        cd /scripts/opm-scraper &&
        python3 -m venv opmscrapervenv &&
        source opmscrapervenv/bin/activate &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        sudo systemctl restart opm-scraper &&
        sudo systemctl status opm-scraper --no-pager
      "
  tags:
    - linux
